window:
  opacity: 0.9

font:
  normal:
    family: JetBrains Mono
  bold:
    family: JetBrains Mono
  italic:
    family: JetBrains Mono
  size: 11.0

colors:
  primary:
    background: '0x141618'

