#!/bin/bash

mkdir -p ~/.config/nvim
cd ~/.config/nvim
if hash nvim 2>/dev/null; then VIM=nvim; else VIM=vim; fi
if [[ $VIM == "nvim" && ! -e ~/.vimrc ]]; then
    echo "> Symlinking vim -> nvim"
    ln -s ~/.config/nvim/init.vim ~/.vimrc
    ln -s ~/.config/nvim ~/.vim
fi
if [[ ! -e autoload/plug.vim ]]; then
    echo "> Installing vim-plug"
    curl --create-dirs -sfLo autoload/plug.vim "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    $VIM +PlugInstall
fi
